[package]
name = "rklipperscreen"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
tokio-tungstenite = "0.29.0"
futures-util = "0.3.32"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.5.0"
input = "0.10.0"
udev = "0.9.3"
libc = "0.2.153"
slint = "1.9.0"
tokio = { version = "1.37.0", features = ["full"] }

[build-dependencies]
slint-build = "1.9.0"

[profile.release]
lto = true
opt-level = 3
