import { ConsolePanel } from "panels/console.slint";
import { FilesPanel } from "panels/files.slint";
import { MovePanel } from "panels/move.slint";
import { TemperaturePanel } from "panels/temperature.slint";
import { MainMenuPanel } from "panels/main_menu.slint";
import { JobStatusPanel } from "panels/job_status.slint";
import { ExtrudePanel } from "panels/extrude.slint";
import { FanPanel } from "panels/fan.slint";
import { BedLevelPanel } from "panels/bed_level.slint";
import { BedMeshPanel } from "panels/bed_mesh.slint";
import { ZCalibratePanel } from "panels/zcalibrate.slint";
import { InputShaperPanel } from "panels/input_shaper.slint";
import { LimitsPanel } from "panels/limits.slint";
import { PressureAdvancePanel } from "panels/pressure_advance.slint";
import { RetractionPanel } from "panels/retraction.slint";
import { FineTunePanel } from "panels/fine_tune.slint";
import { PinsPanel } from "panels/pins.slint";
import { NetworkPanel } from "panels/network.slint";
import { SystemPanel } from "panels/system.slint";
import { SettingsPanel } from "panels/settings.slint";
import { UpdaterPanel } from "panels/updater.slint";
import { PowerPanel } from "panels/power.slint";
import { ShutdownPanel } from "panels/shutdown.slint";
import { CameraPanel } from "panels/camera.slint";
import { SpoolmanPanel } from "panels/spoolman.slint";
import { SpoolEditorPanel } from "panels/spool_editor.slint";
import { GCodeMacrosPanel } from "panels/gcode_macros.slint";
import { ExcludeObjectPanel } from "panels/exclude.slint";
import { LedPanel } from "panels/led.slint";

export {
    ConsolePanel,
    FilesPanel,
    MovePanel,
    TemperaturePanel,
    MainMenuPanel,
    JobStatusPanel,
    ExtrudePanel,
    FanPanel,
    BedLevelPanel,
    BedMeshPanel,
    ZCalibratePanel,
    InputShaperPanel,
    LimitsPanel,
    PressureAdvancePanel,
    RetractionPanel,
    FineTunePanel,
    PinsPanel,
    NetworkPanel,
    SystemPanel,
    SettingsPanel,
    UpdaterPanel,
    PowerPanel,
    ShutdownPanel,
    CameraPanel,
    SpoolmanPanel,
    SpoolEditorPanel,
    GCodeMacrosPanel,
    ExcludeObjectPanel,
    LedPanel
}

export component RKlipperScreen inherits Window {
    width: 800px;
    height: 480px;
    background: #121212;
    
    in-out property <string> bed_temp: "0.0";
    in-out property <string> hotend_temp: "0.0";
    
    VerticalLayout {
        alignment: center;
        spacing: 20px;
        
        Text {
            text: "Hotend: " + root.hotend_temp + " °C";
            font-size: 32px;
            color: #ff5252;
            horizontal-alignment: center;
        }
        Text {
            text: "Bed: " + root.bed_temp + " °C";
            font-size: 32px;
            color: #448aff;
            horizontal-alignment: center;
        }
    }
}