export component RKlipperScreen inherits Window {
    width: 800px;
    height: 480px;
    background: #121212;
    
    in-out property <string> bed_temp: "0.0";
    in-out property <string> hotend_temp: "0.0";
    
    VerticalLayout {
        alignment: center;
        spacing: 20px;
        
        Text {
            text: "Hotend: " + root.hotend_temp + " °C";
            font-size: 32px;
            color: #ff5252;
            horizontal-alignment: center;
        }
        Text {
            text: "Bed: " + root.bed_temp + " °C";
            font-size: 32px;
            color: #448aff;
            horizontal-alignment: center;
        }
    }
}